import { Button, Container, Stack, Tooltip, Divider, Box, Grid } from '@mui/material';
import Head from 'next/head'
import styles from '../../styles/WebServices.module.scss'
import Image from 'next/image'
import ContactUs from '../../components/ContactUs';

const MobileServices = () => {
  return (
    <>
      <Grid container spacing={1} sx={{ display: 'flex' }}>
        <Grid item xs={12} md={6}>
          <img className={styles.image} src='/services/mobile.png' />
        </Grid>
        <Grid item xs={12} md={6} sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
          <Box sx={{ display: 'flex', flexDirection: 'column' }}>
            <h5 className={styles.heading}>Mobile Development</h5>
            <h6 className={styles.description}>
              To understand and meet your requirements, our battle-tested web development team utilises both latest and legacy tools.
            </h6>
            <Button href="#getintouch" className={styles.animatedButton} variant="outlined" color="secondary" sx={{ textTransform: 'none', justifySelf: 'center' }}>Get In Touch</Button>
          </Box>
        </Grid>

      </Grid>

      <Container id="getintouch" maxWidth='lg' sx={{ mb: 2 }}>
        <Head>
          <title>Services | Mobile App Development</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet" />
        </Head>

        <Grid container spacing={1}>
          <Grid item xs={12} md={8}>
            <h2 style={{ color: 'blue' }}>
              We have expertise in the following:
            </h2>
            <h3>Programming Languages.</h3>
            <Stack
              sx={{ alignItems: 'center', justifyContent: { sx: 'center', md: 'left' } }}
              direction="row"
              divider={<Divider orientation="vertical" flexItem />}
              spacing={2}
            >
              <Tooltip title='Java'><img className={styles.logo} src='/services/java.png' width='7%' /></Tooltip>
              <Tooltip title='Javascript'><img className={styles.logo} src='/services/js.png' width='7%' /></Tooltip>
              <Tooltip title='Dart'><img className={styles.logo} src='/services/dart.png' width='7%' /></Tooltip>
            </Stack>
            <h3>UI Frameworks.</h3>
            <Stack
              sx={{ alignItems: 'center', justifyContent: { sx: 'center', md: 'left' } }}
              direction="row"
              divider={<Divider orientation="vertical" flexItem />}
              spacing={2}
            >
              <Tooltip title='React Native'><img className={styles.logo} src='/services/reactnative.png' width='7%' /></Tooltip>
              <Tooltip title='Flutter'><img className={styles.logo} src='/services/flutter.png' width='7%' /></Tooltip>
            </Stack>
            <h3>Database.</h3>
            <Stack
              sx={{ alignItems: 'center', justifyContent: { sx: 'center', md: 'left' } }}
              direction="row"
              divider={<Divider orientation="vertical" flexItem />}
              spacing={2}
            >
              <Tooltip title='MongoDB'><img className={styles.logo} src='/services/mongo.png' width='7%' /></Tooltip>
              <Tooltip title='Firebase'><img className={styles.logo} src='/services/firebase.png' width='3%' /></Tooltip>
            </Stack>
          </Grid>
          <Grid id='getintouch' item xs={12} md={4}>
            <h2 style={{ color: 'blue' }}>
              Get In Touch:
            </h2>
            <ContactUs projectType='web' />
          </Grid>
        </Grid>
      </Container>
    </>
  )
}
export default MobileServices;
