import { Button, Container, Stack, Tooltip, Divider, Box, Grid } from '@mui/material';
import Head from 'next/head'
import styles from '../../styles/WebServices.module.scss'
import Image from 'next/image'
import ContactUs from '../../components/ContactUs';

const MobileServices = () => {
  return (
    <>
      <Box sx={{ display: 'flex' }}>
        {/* <Box> */}
        <img className={styles.image} src='/9.png' />
        {/* </Box> */}
        <Box sx={{display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
          <h5 className={styles.heading}>Mobile App Development.</h5>
          <h6 className={styles.description}>
            To understand and meet your requirements, our battle-tested web development team utilises both latest and legacy tools.
          </h6>
          <Button href="#getintouch" variant="outlined" color="secondary" sx={{ textTransform: 'none', justifySelf: 'center' }}>Get In Touch</Button>
        </Box>
      </Box>

      <Container id="getintouch" maxWidth='lg'>
        <Head>
          <title>Services | Mobile App Development</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet" />
        </Head>

        <Grid container spacing={1}>
        <Grid item xs={8}>
          <h6 className={styles.description}>
            We have expertise in the following:
          </h6>
          <h5 className={styles.logoHeading} >Programming Languages.</h5>
          <Stack
            sx={{ alignItems: 'center', justifyContent: 'left' }}
            direction="row"
            divider={<Divider orientation="vertical" flexItem />}
            spacing={2}
          >
            <Tooltip title='Java'><img className={styles.logo} src='/services/java.png' width='7%' /></Tooltip>
            <Tooltip title='Javascript'><img className={styles.logo} src='/services/js.png' width='7%' /></Tooltip>
            <Tooltip title='Dart'><img className={styles.logo} src='/services/dart.png' width='7%' /></Tooltip>
          </Stack>
          <h5 className={styles.logoHeading} >UI Frameworks.</h5>
          <Stack
            sx={{ alignItems: 'center', justifyContent: 'left' }}
            direction="row"
            divider={<Divider orientation="vertical" flexItem />}
            spacing={2}
          >
            <Tooltip title='React Native'><img className={styles.logo} src='/services/reactnative.png' width='7%' /></Tooltip>
            <Tooltip title='Flutter'><img className={styles.logo} src='/services/flutter.png' width='7%' /></Tooltip>
          </Stack>
          <h5 className={styles.logoHeading} >Database.</h5>
          <Stack
            sx={{ alignItems: 'center', justifyContent: 'left' }}
            direction="row"
            divider={<Divider orientation="vertical" flexItem />}
            spacing={2}
          >
            <Tooltip title='MongoDB'><img className={styles.logo} src='/services/mongo.png' width='7%' /></Tooltip>
            <Tooltip title='Firebase'><img className={styles.logo} src='/services/firebase.png' width='3%' /></Tooltip>
          </Stack>
        </Grid>
        <Grid id='getintouch' item xs={4}>
        <h6 className={styles.description}>
            Get In Touch:
          </h6>
          <ContactUs projectType='mobile' />
        </Grid>
          </Grid>
        
      </Container>
    </>
  )
}
export default MobileServices;
