import { Button, Container, Stack, Item, Divider, Box, Grid } from '@mui/material';
import Head from 'next/head'
import styles from '../../styles/WebServices.module.scss'
import Image from 'next/image'
import ContactUs from '../../components/ContactUs';

const WebServices = () => {
  return (
    <>
      <Box sx={{ display: 'flex' }}>
        {/* <Box> */}
        <img className={styles.image} src='/5.png' />
        {/* </Box> */}
        <Box sx={{display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
          <h5 className={styles.heading}>Web Development.</h5>
          <h6 className={styles.description}>
            To understand and meet your requirements, our battle-tested web development team utilises both latest and legacy tools.
          </h6>
          <Button href="#getintouch" variant="outlined" color="secondary" sx={{ textTransform: 'none', justifySelf: 'center' }}>Get In Touch</Button>
        </Box>
      </Box>

      <Container id="getintouch" maxWidth='lg'>
        <Head>
          <title>Services | Web Development</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet" />
        </Head>

        <Grid container spacing={1}>
        <Grid item xs={8}>
          <h6 className={styles.description}>
            We have expertise in the following:
          </h6>
          <h5 className={styles.logoHeading} >Programming Languages.</h5>
          <Stack
            sx={{ alignItems: 'center', justifyContent: 'left' }}
            direction="row"
            divider={<Divider orientation="vertical" flexItem />}
            spacing={2}
          >
            <img className={styles.logo} src='/services/csharp.png' width='7%' />
            <img className={styles.logo} src='/services/js.png' width='7%' />
            <img className={styles.logo} src='/services/ts.png' width='7%' />
            <img className={styles.logo} src='/services/php.png' width='7%' />
          </Stack>
          <h5 className={styles.logoHeading} >Web Frameworks.</h5>
          <Stack
            sx={{ alignItems: 'center', justifyContent: 'left' }}
            direction="row"
            divider={<Divider orientation="vertical" flexItem />}
            spacing={2}
          >
            <img className={styles.logo} src='/services/asp.png' width='7%' />
            <img className={styles.logo} src='/services/next.png' width='7%' />
            <img className={styles.logo} src='/services/laravel.png' width='7%' />
          </Stack>
          <h5 className={styles.logoHeading} >Front-end Stack.</h5>
          <Stack
            sx={{ alignItems: 'center', justifyContent: 'left' }}
            direction="row"
            divider={<Divider orientation="vertical" flexItem />}
            spacing={2}
          >
            <img className={styles.logo} src='/services/html.png' width='7%' />
            <img className={styles.logo} src='/services/css.png' width='7%' />
            <img className={styles.logo} src='/services/bootstrap.png' width='7%' />
            <img className={styles.logo} src='/services/react.png' width='7%' />
            <img className={styles.logo} src='/services/mui.png' width='7%' />
            <img className={styles.logo} src='/services/antd.png' width='7%' />
            <img className={styles.logo} src='/services/sass.png' width='7%' />
            <img className={styles.logo} src='/services/jquery.png' width='7%' />
          </Stack>
          <h5 className={styles.logoHeading} >Back-end.</h5>
          <Stack
            sx={{ alignItems: 'center', justifyContent: 'left' }}
            direction="row"
            divider={<Divider orientation="vertical" flexItem />}
            spacing={2}
          >
            <img className={styles.logo} src='/services/node.png' width='7%' />
            <img className={styles.logo} src='/services/net.png' width='7%' />
            <img className={styles.logo} src='/services/vba.png' width='7%' />
          </Stack>
          <h5 className={styles.logoHeading} >Database.</h5>
          <Stack
            sx={{ alignItems: 'center', justifyContent: 'left' }}
            direction="row"
            divider={<Divider orientation="vertical" flexItem />}
            spacing={2}
          >
            <img className={styles.logo} src='/services/mssql.png' width='7%' />
            <img className={styles.logo} src='/services/mysql.png' width='7%' />
            <img className={styles.logo} src='/services/mongo.png' width='7%' />
            <img className={styles.logo} src='/services/firebase.png' width='3%' />
          </Stack>
        </Grid>
        <Grid id='getintouch' item xs={4}>
        <h6 className={styles.description}>
            Get In Touch:
          </h6>
          <ContactUs />
        </Grid>
          </Grid>
        
      </Container>
    </>
  )
}
export default WebServices;
