import { Button, Container } from '@mui/material';
import Head from 'next/head'
import styles from '../../styles/WebServices.module.scss'

const WebServices = () => {
  return (
    <>
      <img src='/5.png' width="100%" />
      <Container maxWidth='lg'>
        <Head>
          <title>Web Services</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet" />
        </Head>
        <h1 className={styles.heading}>Web Development.</h1>
        <h6 className={styles.description}>
        To understand and meet your requirements, our battle-tested web development team utilises both latest and legacy tools.
        </h6>
        <h1>Front-end.</h1>
      </Container>
    </>
  )
}
export default WebServices;
