import Head from 'next/head'
import styles from '../../styles/OurTeam.module.scss'
import { Container, Box, Grid, List, Divider, ListItem, ListItemText, ListItemIcon, Button } from '@mui/material'
import { BrowserView, isDesktop, isMobile, MobileView } from 'react-device-detect';
import { useEffect, useLayoutEffect, useState } from 'react';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';

const OurTeam = () => {
    const [source, setSource] = useState('');
    useLayoutEffect(() => {
        isMobile ? setSource('/ourteammobile.png') : setSource('/ourteamdesktop.png')
    }, [])
    return (
        <>
            <img src={source} width="100%" />
            <Container maxWidth="lg">
                <Head>
                    <title>Our Team</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel="preconnect" href="https://fonts.googleapis.com" />
                    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                    <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet" />
                </Head>
                <h1 className={styles.heading}>Our Team.</h1>
                <h6 className={styles.description2}>Individual dedication to a group effort is what makes a team, a company, a community, or a civilization work.
                    At Magical Digits we push each other to bring out the best in all of us. We believe in enjoying the process rather than concentrating solely on the goal.
                    We are a team of over 20 professionals who work both on-site and remotely.</h6>
                <h6 className={styles.heading2}>
                    Magical Digits Administration.
                </h6>
                <Grid container sx={{ my: 2 }}>
                    <Grid item xs={12} sm={6} md={4}>
                        <Card>
                            <CardMedia
                                component="img"
                                width='100%'
                                image="/ourteammobile.png"
                                alt="Ozair Khalid"
                            />
                            <CardContent>
                            </CardContent>
                            <CardActions>
                                {/* <Button size="small">Share</Button>
                                <Button size="small">Learn More</Button> */}
                            </CardActions>
                        </Card>
                    </Grid>
                    <Grid item xs={12} sm={6} md={4}>
                        <Card>
                            <CardMedia
                                component="img"
                                width='100%'
                                image="/ourteammobile.png"
                                alt="Ozair Khalid"
                            />
                            <CardContent>
                            </CardContent>
                            <CardActions>
                                {/* <Button size="small">Share</Button>
                                <Button size="small">Learn More</Button> */}
                            </CardActions>
                        </Card>
                    </Grid>
                    <Grid item xs={12} sm={6} md={4}>
                        <Card>
                            <CardMedia
                                component="img"
                                width='100%'
                                image="/ourteammobile.png"
                                alt="Ozair Khalid"
                            />
                            <CardContent>
                            </CardContent>
                            <CardActions>
                                {/* <Button size="small">Share</Button>
                                <Button size="small">Learn More</Button> */}
                            </CardActions>
                        </Card>
                    </Grid>
                    <Grid item xs={12} sm={6} md={4}>
                        <Card>
                            <CardMedia
                                component="img"
                                width='100%'
                                image="/ourteammobile.png"
                                alt="Ozair Khalid"
                            />
                            <CardContent>
                            </CardContent>
                            <CardActions>
                                {/* <Button size="small">Share</Button>
                                <Button size="small">Learn More</Button> */}
                            </CardActions>
                        </Card>
                    </Grid>
                    <Grid item xs={12} sm={6} md={4}>
                        <Card>
                            <CardMedia
                                component="img"
                                width='100%'
                                image="/ourteammobile.png"
                                alt="Ozair Khalid"
                            />
                            <CardContent>
                            </CardContent>
                            <CardActions>
                                {/* <Button size="small">Share</Button>
                                <Button size="small">Learn More</Button> */}
                            </CardActions>
                        </Card>
                    </Grid>
                    <Grid item xs={12} sm={6} md={4}>
                        <Card>
                            <CardMedia
                                component="img"
                                width='100%'
                                image="/ourteammobile.png"
                                alt="Ozair Khalid"
                            />
                            <CardContent>
                            </CardContent>
                            <CardActions>
                                {/* <Button size="small">Share</Button>
                                <Button size="small">Learn More</Button> */}
                            </CardActions>
                        </Card>
                    </Grid>
                </Grid>

            </Container>
        </>
    )
}

export default OurTeam;