import Head from 'next/head'
import styles from '../styles/Careers.module.scss'
import { Container, Box, Grid, List, Divider, ListItem, ListItemText, ListItemIcon, Button, Paper, Chip } from '@mui/material'
import { BrowserView, isDesktop, isMobile, MobileView } from 'react-device-detect';
import { useEffect, useLayoutEffect, useState } from 'react';
import PaidIcon from '@mui/icons-material/Paid';
import FitnessCenterIcon from '@mui/icons-material/FitnessCenter';
import AccessTimeIcon from '@mui/icons-material/AccessTime';
import DirectionsCarIcon from '@mui/icons-material/DirectionsCar';
import CoffeeIcon from '@mui/icons-material/Coffee';
import AutoGraphIcon from '@mui/icons-material/AutoGraph';
import CalendarMonthIcon from '@mui/icons-material/CalendarMonth';
import GroupsIcon from '@mui/icons-material/Groups';
import CardGiftcardIcon from '@mui/icons-material/CardGiftcard';
import MoneyIcon from '@mui/icons-material/Money';
import WorkIcon from '@mui/icons-material/Work';

const Careers = () => {
    const [source, setSource] = useState('');
    useLayoutEffect(() => {
        isMobile ? setSource('/careersmobile.png') : setSource('/careersdesktop.png')
    }, [])
    return (
        <>
            <img src={source} width="100%" />
            <Container maxWidth="lg">
                <Head>
                    <title>Careers</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel="preconnect" href="https://fonts.googleapis.com" />
                    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                    <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet" />
                </Head>
                <h1 className={styles.heading}>Careers.</h1>
                <h6 className={styles.description}>We only work with the finest, for the finest.</h6>
                <Box sx={{ textAlign: 'center' }}><Button
                    key='Contact us'
                    href='#jobopenings'
                    variant="outlined"
                    color="secondary"
                    className={styles.animatedButton}
                >
                    View Current Openings
                </Button></Box>

                <h6 className={styles.heading2}>Why Magical Digits?</h6>

                <Grid container sx={{ my: 2 }}>
                    <Grid item xs={12} md={6}>
                        <List>
                            <ListItem>
                                <ListItemIcon>
                                    <PaidIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='Market leading salary.' />
                            </ListItem>

                            <Divider variant="inset" component="li" />

                            <ListItem>
                                <ListItemIcon>
                                    <AccessTimeIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='Flexible working hours.' />
                            </ListItem>

                            <Divider variant="inset" component="li" />

                            <ListItem>
                                <ListItemIcon>
                                    <AutoGraphIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='Exponential growth in both salary and rank.' />
                            </ListItem>

                            <Divider variant="inset" component="li" />

                            <ListItem>
                                <ListItemIcon>
                                    <DirectionsCarIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='Conveyance allowance.' />
                            </ListItem>

                            <Divider variant="inset" component="li" />

                            <ListItem>
                                <ListItemIcon>
                                    <CardGiftcardIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='Performance bonuses.' />
                            </ListItem>

                        </List>
                    </Grid>
                    <Grid item xs={12} md={6}>

                        <List>
                            <Divider sx={{ display: { md: 'none' } }} variant="inset" component="li" />
                            <ListItem>
                                <ListItemIcon>
                                    <CalendarMonthIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='Paid leaves.' />
                            </ListItem>

                            <Divider variant="inset" component="li" />

                            <ListItem>
                                <ListItemIcon>
                                    <CoffeeIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='Free unlimited tea, coffee and snacks among other things.' />
                            </ListItem>

                            <Divider variant="inset" component="li" />
                            <ListItem>
                                <ListItemIcon>
                                    <FitnessCenterIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='In-house fitness gym.' />
                            </ListItem>

                            <Divider variant="inset" component="li" />

                            <ListItem>
                                <ListItemIcon>
                                    <MoneyIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='Leave encashments.' />
                            </ListItem>

                            <Divider variant="inset" component="li" />

                            <ListItem>
                                <ListItemIcon>
                                    <GroupsIcon fontSize='large' color='primary' />
                                </ListItemIcon>

                                <ListItemText primary='Friendly working environment.' />
                            </ListItem>

                        </List>
                    </Grid>
                </Grid>

                <h6 className={styles.heading2}>Current Job Openings.</h6>
                <Box id='jobopenings' sx={{ display: 'flex', justifyContent: 'space-evenly', mb: 2 }}>
                    <Paper elevation={4} sx={{ p: 3 }}>
                        <h3>Junior Software Engineer</h3>
                        <Chip size="small" label="1 Position" color='secondary' />
                        <p>Karachi, <img src='https://flagcdn.com/w20/pk.png' /></p>
                        <Box sx={{ display: 'flex', alignItems: 'center' }}><WorkIcon fontSize='small' color='primary' />&nbsp;<span>Permanent</span></Box>
                        <Box sx={{ display: 'flex', alignItems: 'center' }}><AccessTimeIcon fontSize='small' color='primary' />&nbsp;<span>Applications closing on May 15, 2022</span></Box>
                        <Box sx={{ textAlign: 'center' }}><Button
                        size='small'
                            key='Contact us'
                            href='#jobopenings'
                            variant="outlined"
                            color="secondary"
                            className={styles.animatedButton}
                            sx={{mt:1}}
                        >
                            View Details
                        </Button></Box>
                    </Paper>
                    <Paper elevation={4} sx={{ p: 3 }}>
                        <h3>Associate Software Engineer</h3>
                        <Chip size="small" label="4 Positions" color='secondary' />
                        <p>Karachi, <img src='https://flagcdn.com/w20/pk.png' /></p>
                        <Box sx={{ display: 'flex', alignItems: 'center' }}><WorkIcon fontSize='small' color='primary' />&nbsp;<span>Permanent</span></Box>
                        <Box sx={{ display: 'flex', alignItems: 'center' }}><AccessTimeIcon fontSize='small' color='primary' />&nbsp;<span>Applications closing on June 30, 2022</span></Box>
                        <Box sx={{ textAlign: 'center' }}><Button
                        size='small'
                            key='Contact us'
                            href='#jobopenings'
                            variant="outlined"
                            color="secondary"
                            className={styles.animatedButton}
                            sx={{mt:1}}
                        >
                            View Details
                        </Button></Box>
                    </Paper>
                    <Paper elevation={4} sx={{ p: 3 }}>
                        <h3>Junior Mobile Developer</h3>
                        <Chip size="small" label="1 Position" color='secondary' />
                        <p>Karachi, <img src='https://flagcdn.com/w20/pk.png' /></p>
                        <Box sx={{ display: 'flex', alignItems: 'center' }}><WorkIcon fontSize='small' color='primary' />&nbsp;<span>Permanent</span></Box>
                        <Box sx={{ display: 'flex', alignItems: 'center' }}><AccessTimeIcon fontSize='small' color='primary' />&nbsp;<span>Applications closing on May 25, 2022</span></Box>
                        <Box sx={{ textAlign: 'center' }}><Button
                        size='small'
                            key='Contact us'
                            href='#jobopenings'
                            variant="outlined"
                            color="secondary"
                            className={styles.animatedButton}
                            sx={{mt:1}}
                        >
                            View Details
                        </Button></Box>
                    </Paper>
                </Box>


            </Container>
        </>
    )
}
export default Careers;