import Head from 'next/head'
import styles from '../styles/ContactUs.module.scss'
import { Container, Box, Grid, List, Divider, ListItem, ListItemText, ListItemIcon } from '@mui/material'
import ContactUs from '../components/ContactUs';
import LocationOnIcon from '@mui/icons-material/LocationOn';
import PhoneIcon from '@mui/icons-material/Phone';
import MailIcon from '@mui/icons-material/Mail';
import WhatsAppIcon from '@mui/icons-material/WhatsApp';


const ContactUsPage = () => {
    return (
        <>
            <Box sx={{ display: { xs: 'none', sm: 'flex' } }}><img src='https://firebasestorage.googleapis.com/v0/b/magicaldigits-web.appspot.com/o/home%2Fcontactusdesktop.png?alt=media&token=7a397b81-3fff-4aa0-a7a8-db55a2360c26' width="100%" /></Box>
            <Box sx={{ display: { xs: 'flex', sm: 'none' } }}><img src='https://firebasestorage.googleapis.com/v0/b/magicaldigits-web.appspot.com/o/home%2Fcontactusmobile.png?alt=media&token=577ecb15-02b7-44e3-8ac0-bf82c7d1469f' width="100%" /></Box>
            <Container maxWidth="lg">
                <Head>
                    <title>Contact Us</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel="preconnect" href="https://fonts.googleapis.com" />
                    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                    <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet" />
                </Head>
                <h1 className={styles.heading}>Contact Us.</h1>

                <Grid container sx={{ my: 2 }}>
                    <Grid item xs={12} md={8}>
                        <ContactUs projectType='' />
                    </Grid>
                    <Grid item xs={12} md={4} sx={{ alignSelf: 'center' }}>
                        <List>
                            <ListItem>
                                <ListItemIcon>
                                    <PhoneIcon fontSize='large' color='secondary' />
                                </ListItemIcon>

                                <a href='tel:+922134982756'><ListItemText primary='+92-21-34982756' /></a>
                            </ListItem>

                            <Divider variant="inset" component="li" />

                            <ListItem>
                                <ListItemIcon>
                                    <MailIcon fontSize='large' color='secondary' />
                                </ListItemIcon>

                                <a target='_blank' href='mailto:info@magicaldigits.com'><ListItemText primary='info@magicaldigits.com' /></a>
                            </ListItem>

                            <Divider variant="inset" component="li" />
                            <ListItem>
                                <ListItemIcon>
                                    <WhatsAppIcon fontSize='large' color='secondary' />
                                </ListItemIcon>

                                <a target='_blank' href='https://api.whatsapp.com/send?phone=923222252364'><ListItemText primary='+923222252364' /></a>
                            </ListItem>
                            <Divider variant="inset" component="li" />
                            <ListItem>
                                <ListItemIcon>
                                    <LocationOnIcon fontSize='large' color='secondary' />
                                </ListItemIcon>

                                <ListItemText primary='Suite # 205, Gulshan Trade Center Block 5
                                        Gulshan-e-Iqbal, Karachi, Pakistan.' />
                            </ListItem>

                        </List>
                    </Grid>
                </Grid>
                <h6 className={styles.heading2}>
                    Visit Us.
                </h6>
                <Box className={styles.mapouter}>
                    <div className={styles.gmap_canvas}>
                        <iframe className={styles.gmap_iframe} width="100%" frameBorder="0" scrolling="no" marginHeight="0" marginWidth="0" src="https://maps.google.com/maps?width=600&amp;height=400&amp;hl=en&amp;q=Magical Digits&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
                    </div>
                </Box>


            </Container>
        </>
    )
}
export default ContactUsPage;